version: "3.9"

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: umzug
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017}
      DB_NAME: ${DB_NAME:-umzug}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-change-me-in-production}
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8001}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo-data:
